# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6dbdfe4bcd4cc4b9cf9e2b46dda488e786d35a93fc29ab911c8c539835e965791f49587423aa4f2e0fe8f6966ab42e097ed3de6a41b21ced8210f6d4f174e4d

test:
  secret_key_base: bb53b7cf649ebba8e24bbfd62d906df214dc7e8e3de1767b76c132fdc39ca79e1e367181cc4d9299e67cd41ff6c72d88cf03464928cfc7890b50ed3eaaed2c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
